[workspace]
resolver = "2"
members = [
    "core",
    "core_stdlib",
    "codelib-gen",
    "runtime/core",
    "runtime/test_rt_dylib",
    "runtime-langs/luau",
    "runtime-langs/python",
    "package-manager",
    "package-server"
]

[profile.release]
opt-level = 2
