[package]
name = "comline-codelib-gen-lua"
version = "0.1.0"
edition = "2021"


[dependencies]
comline-codelib-gen = { path = "../_core" }

mlua =  { version = "0.9.1", features = ["lua51", "module"] }
