[package]
name = "comline-codelib-gen-lua"
version = "0.1.0"
edition = "2021"


[dependencies]
comline-core = { version = "0.1.0", path = "../../core" }
comline-codelib-gen = { path = "../_core" }

mlua =  { version = "0.9.2", features = ["lua51", "module"] }
eyre = "0.6.11"
once_cell = "1.18.0"
