site_name: Comline

nav:
  - Home: 'index.md'
  - Project Planing: 'planning.md'
  - 'IDL (Interface Description Language)':
    - 'idl/index.md'
    - Settings: 'idl/settings.md'
    - Structure: 'idl/structure.md'
    - Enum: 'idl/enum.md'
    - Protocol: 'idl/protocol.md'
    - Docstrings: "idl/docstrings.md"
  - 'IR (Intermediate Representation)':
      - 'ir/index.md'


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime


# TODO: The social plugin is disabled due to not Cairo lib not being available on Nix
#plugins:
#  - social

#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#     link: https://github.com/james-willett
#   - icon: fontawesome/brands/twitter
#     link: https://twitter.com/TheJamesWillett
#   - icon: fontawesome/brands/linkedin
#     link: https://www.linkedin.com/in/willettjames/

  version:
    provider: mike
    default: stable

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: |
  &copy; 2023 <a href="https://git.ablecorp.us/DOOME1M8Cover/comline-rs"  target="_blank" rel="noopener">comline-rs</a>
